#!/bin/sh

uci set network.lan.ifname='eth0'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.31.254'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.31.1'
uci set network.lan.dns='192.168.31.1'
uci set network.lan.delegate='0'
uci -q delete network.lan.type
uci -q delete network.lan.ip6assign
uci -q delete network.globals.ula_prefix
uci set network.WireGuard='interface'
uci set network.WireGuard.proto='wireguard'
uci set network.WireGuard.delegate='0'
uci set network.WireGuard.private_key='IK7iRJQuXXhmWImk/WajnoJH2GQXi7DuChrsZP0pNWA='
uci set network.WireGuard.listen_port='2000'
uci add_list network.WireGuard.addresses='192.168.100.1/24'
uci set network.wgclient='wireguard_WireGuard'
uci set network.wgclient.public_key='HxIQxXtLKyBBWT2gMzGIPZBLmPK7spiXZ58k/0upviQ='
uci set network.wgclient.preshared_key='RpONxptGpHcj/Plfunl4gREeJ6W50UX28G5XQHJz0BA='
uci set network.wgclient.route_allowed_ips='1'
uci add_list network.wgclient.allowed_ips='192.168.100.2/32'
uci commit network

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
